[project]
name = "colordemo"
version = "0.1"
description = "RGB queries on xterm-like terminals"
readme = "README.md"
requires-python = ">=3.0"

[project.scripts]
colordemo = "colordemo.__main__:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
